[project]
name = "dk-parse"
version = "1"
dependencies = ["requests", "rich", "fastapi", "uvicorn[standard]", "aiohttp", "sentry-sdk[fastapi]"]

[project.optional-dependencies]
dev = ["pytest", "black", "flake8", "mangum"]
